baseURL = 'https://blog.elnu.com/'
languageCode = 'en-us'
title = "Elnu's Blog"
theme = 'sakura-hugo-theme'
enableEmoji = true
paginate = 3

[params]
	Author = 'Elnu'
	AuthorProfile = 'https://elnu.com/'
	AuthorTwitter = 'ElnuDev'
	SiteTwitter = 'ElnuDev'
	MatomoURL = 'matomo.elnu.com'
	MatomoSiteId = '5'
	HomepageHeader = '<a href="https://elnu.com/">&laquo; Back to profile</a>'
	Theme = 'earthly'
	ThemeColor = '#007559'

[permalinks]
	pages = '/:title'
	posts = '/:year/:month/:title/'

[taxonomies]
	tag = 'tags'

[markup]
	[markup.highlight]
		style = 'friendly'
